### ISSUE TITLE
Research for implementing cpenv in my studio

### ISSUE THREAD

**Issue by fabiangeisler** [cpenv/cpenv#52]
Hi @danbradham ! 

I hope this is the right place to talk to you about cpenv. Let me know if not and we take it somewhere else.
I stumbled across cpenv and I really like it so far. That is why I am currently evaluating whether it is feasible to implement in our studio, but I still have a few questions about it:
1. Is it possible to have the environment configurations on a per project basis? 
    We currently have some projects that run different versions of Arnold, which needs to be kept this way.
2. Is it possible to have the configurations nested inside each other? 
    Like global- than a project-configuration and then maybe even a shot configuration? So we can have certain plugins on a global scale (like the Maya security plugin) and other plugins on a project level (like Arnold) and others on a shot level where we need this "new bleeding edge new feature" of some plugin. 

That's it for now, but there will probably be some more questions coming as I move along with the research. 🙂 

Cheers, 
Fabian

**Comment by fabiangeisler** [comment]
To answer my own questions:
> 1. Is it possible to have the environment configurations on a per project basis?

Yes, it is. It is actually **only** possible to have the on a per project basis (at least in the tk-cpenv ShotGrid implementation)
> 2. Is it possible to have the configurations nested inside each other?

No, it is not possible to have nested environments. But modules can of course overwrite each others environment variables, which can be used for the behaviour I want.

**Comment by fabiangeisler** [comment]
Next question:
How do you load an environment for software versions that do not have a SGTK engine?
Like Mudbox, Mocha or Speedtree for example.

**Comment by fabiangeisler** [comment]
> How do you load an environment for software versions that do not have a SGTK engine? 

By the looks of it, it is not possible at the moment, which is kind of a deal breaker for me. However it seems to be not terribly complicated to implement it. The tricky question is: How should it be implemented, in order to be user friendly and maintainable? Linking environment entities and software entities together would be nice but could also get out of hand with a lot of projects over time...

**Comment by fabiangeisler** [comment]
New Question: 
What is the best approach when you want to create a module for a plugin that has files for multiple software versions?
Example: Optical Flares v.0.86 ships with binaries for Nuke10.0 - Nuke12.2. So rather than setting up Optical Flares for each Nuke version individually, it would be nice to have a environment variable ('SOFTWARE_VERSION' or something similar) that could be used inside the module.yml. This however, is hard to get if before you launch the software. It'd be possible in SGTK but kinda defeats the purpose of the modules if they do not work on their own without setting an environment variable up front. Kinda tricky. Do you have a good way of doing that?

**Comment by danbradham** [comment]
Thanks for answering your own questions, I was a bit busy this week. Let me see what I can add to what you've discovered.

**Comment by danbradham** [comment]
> Is it possible to have the configurations nested inside each other?

As you've found this is not strictly possible but it is doable by using a module specifically for overriding environment variables. In my studio I've setup an `overrides` module that sits as the final requirement in our Environments. When releasing a new ShotGrid config, if any changes to environment variables are required for this new ShotGrid config, I release a new version of the `overrides` module with the same version number I used for the ShotGrid config.

> How do you load an environment for software versions that do not have a SGTK engine?

This is a great question and I have a follow-up for you. Do you use ShotGrid Desktop to launch these applications as well via Software Entities, just leaving the `Software.engine` field blank? The `tk-cpenv` app looks up Environments based on `engine_name` and `software_version`. I think it would be fairly straight-forward to make the Environment lookup also check the `Software.code` field rather than just the `Software.engine` field. This is definitely something I'd like to support.

For local, terminal usage, you can save an Environment once you've activated a set of requirements. For example:
```
> cpenv activate maya-2023 mtoa-5.2.0-2023
...
> cpenv env save Maya2022
> exit
> cpenv activate --env Maya2022
> maya -proj "/your/maya/workspace/" -file "/your/maya/workspace/scene.mb"
```

> What is the best approach when you want to create a module for a plugin that has files for multiple software versions?
Example: Optical Flares v1.0.86 ships with 7 binaries for Nuke10.0 - Nuke12.2. So rather than setting up Optical Flares for each Nuke version individually, it would be nice to have a environment variable ('SOFTWARE_VERSION' or something similar) that could be used inside the module.yml. This however, is hard to get before you launch the software. It'd be possible in SGTK but kinda defeats the purpose of the modules, if they do not work on their own without setting an environment variable up front. Kinda tricky. Do you have a good way of doing that?

This is another great question. The approach you described with the 'SOFTWARE_VERSION' environment variable is very usefl. I always have a cpenv module for each DCC and typically include a version environment variable to use in other modules. 

To use your example, we could have a module `nuke-12.2` that sets an environment variable `NUKEVER`. Then, in our `optical_flares-1.0.86` module we could use that environment variable to choose the appropriate binary directory. I personally use this approach for Cinema4D and Redshift. Other DCCs have their own package files like Houdini .json files and Maya .mod files, these are great because they give you access to the application version number!

I just created repositories for [cinema4d](https://github.com/cpenv/cinema4d) and [redshift](https://github.com/cpenv/redshift) modules as a concrete example for you.

Another approach I've taken is to create DCC specific versions of modules. For Arnold for Maya, I have modules like `mtoa-5.2.0-2022` and `mtoa-5.2.0-2023`. Then in ShotGrid I have an Environment per software version like, `Autodesk Maya 2022` and `Autodesk Maya 2023`, and these use the appropriate `mtoa` module version. I chose this method for `mtoa` because the plugin is released with different installers for each DCC version which made this approach a natural fit. Redshift on the other hand, ships a giant directory that includes plugins for all DCCs and DCC versions.

**Comment by fabiangeisler** [comment]
Hi Dan!
I guess your answer deserves a medal, with 3 questions answered, 2 example repos and 1 extra issue! 😄 🥇 Thank you for taking the time to write that up! Much appreciated!
> Do you use ShotGrid Desktop to launch these applications as well via Software Entities, just leaving the Software.engine field blank?

Yes, we do. It is our company policy that you have to launch software through ShotGrid (Web or Desktop) in order to get Pipeline support with it. We use some custom starter scripts to control the environment of the DCCs, which works ok but cpenv (or rez for that matter) are more powerful. There is also one special case for MotionBuilder where we decided to not use the SGTK implementation, but still make it launchable through SG Desktop. So the MotionBuilder software entity does not have the `engine` field filled at our studio.

>  I've setup an `overrides` module that sits as the final requirement in our Environments. 

That sounds reasonable. I still like the idea of nested environments, but maybe that is just me overcomplicating things. An `overrides` module could probably do everything I need.

> To use your example, we could have a module `nuke-12.2` that sets an environment variable `NUKEVER`.

That makes a lot of sense. It probably makes sense anyway to have such a module for some more general environment variables, like license servers and such.

So far so good. I can see that this could work for us (if https://github.com/cpenv/tk-cpenv/issues/17 is fixed that is 😉 ), I will dig around some more and see what other questions come up. 🙂 Thanks again for your answers and examples!

**Comment by fabiangeisler** [comment]
New Question:
The [module_paths](https://github.com/cpenv/tk-cpenv/blob/8f1b40de35bc618bfb1baf407df16831908e9364/info.yml#L44) in the `tk-cpenv` config: will modules in these paths be downloaded into one of the local repos? So if I point these paths to a shared server location will the modules be used from that server or will they be cached and than used from your local hard drive?
One related Question: Is there a way to tell `cpenv` when to cache locally from a directory and when not?

**Comment by danbradham** [comment]
If a module is found in a path in `module_paths` it will be used directly. It takes each of the paths in `module_paths` and treats them as `LocalRepo`s to be precise. Currently there is no way to force a module to be localized to a users "home" `LocalRepo`, although that is a very interesting concept that I had not considered.  This is something I've had in the back of my mind for awhile, I'd like to create a RemoteRepo class as well that will treat a local file path as if it were always remote. That would force modules resolved in those repos to be localized to your home repo prior to activation.

In the meantime, there is a `copy` command one could use to manually copy modules from one repo to another. In that scenario you would want to configure a named LocalRepo yourself if you wanted to use it from the CLI. For example:

```
cpenv repo add --type=local network_share_repo --path=//network_share/cpenv/modules
cpenv copy your_repo-0.1.0 --from_repo=network_share_repo --to_repo=home
```

Repos can also be configured manually by editing the `$CPENV_HOME/config.yml` file or you constructed at runtime using the python api and registered with `cpenv.add_repo`.

Just a heads up, I'm about to take a vacation for a couple of weeks so I may be a bit slow to respond to your questions. I'll make an effort to address the software entities issue when I return, but you're more than welcome to create a PR if you feel so inclined =).

**Comment by danbradham** [comment]
@fabiangeisler I had a bit of free time today and was able to add support for Software without toolkit engines. Hope this works for you.

https://github.com/cpenv/tk-cpenv/releases/tag/v0.5.10

I'm going to close this issue. Feel free to open additional issues for future questions. Thank you for your interest in cpenv!

**Comment by fabiangeisler** [comment]
@danbradham Thanks so much for your explanation and for the quick implementation of the bug fix! I will try it out today. If more questions arise, I will continue in another issue as you suggested (Is enabling "Discussions" on your repo an option for you? I kinda like it more for answering questions and discussing new features, so "Issues" is not cluttered with that.) Have fun on your vacation!

**Comment by danbradham** [comment]
Good idea, discussions are enabled!
