### ISSUE TITLE
arguments aren't being passed to modules...

### ISSUE THREAD

**Issue by mgcollie** [cpenv/cpenv#9]
I think line 177 in cpenv/__main__.py should be:

api.launch(module_name, args)

instead of:

api.launch(module_name)

**Comment by danbradham** [comment]
Fixed in version 0.3.5

To make sure you're arguments get passed properly you need to separate the launch command and the arguments using -- as described in the [click documentation](http://click.pocoo.org/5/arguments/#option-like-arguments). For example:

cpenv launch maya2017 -- -h

You can see how this would be a problem without the --, because -h --help will get consumed by click and not passed through without it. Give this a try to see it fail:

cpenv launch maya2017 -h

**Comment by mgcollie** [comment]
Thanks for the quick fix Dan.  Duly noted regarding the launch arguments.
